import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/nav'
import TopLeftImg from './components/TopLeftImg'

// fonts
import { Sora } from "next/font/google"; '@next/font/google'

//  font assing
const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"page bg-site text-white bg-cover bg-no-repeat ${sora.vaiable} font-sora relative "}>
        <TopLeftImg/>
        <Navbar/>
        
        {children}</body>
    </html>
  )
}
